version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: simple-forum-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped

